apiVersion: apps/v1
kind: Deployment
metadata:
    name: dep-kaecses-dev-1
    labels:
        app: srvkaecsesdev1
spec:
    replicas: 1
    selector:
        matchLabels:
            app: srvkaecsesdev1
    template: 
        metadata:
            labels:
                app: srvkaecsesdev1
        spec:
            containers:
            - name: k8s-demo
              image: acrgithubaction.azurecr.io/nginx:v1
              ports:
              - containerPort: 80
            imagePullSecrets:
            - name: githubactionsecret
---            
apiVersion: v1
kind: Service
metadata:
    name: srvkaecsesdev1
    annotations: 
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-dns-label-name: srvkaecsesdev1
    labels:
        app: srvkaecsesdev1
spec:
    ports:
        - name: http-port
          port: 80
          targetPort: 80
    selector: 
        app: srvkaecsesdev1
    type: LoadBalancer
